### DISCUSSION TITLE
Terraform fmt in the same job as terraform plan?

### DISCUSSION THREAD

**Discussion by cberge908** [dflook/terraform-github-actions#150] [Q&A] [answered]
Quick question: Is there any option to run `terraform fmt` in the same action as the `terraform plan`?
I'm running my plan action with the on.pull_request trigger. The job step order is checkout, fmt, plan. Unfortunately the fmt steps seems to be ignored. Is there any solution for that? I don't want to generate separate pull requests to fix the format only, but rather do it in the same job as the plan.

**Comment by dflook** [comment]
Yes, you can use `dflook/terraform-fmt` and `dflook/terraform-plan` in the same job.
When you say it is ignored, what do you mean?

**Comment by cberge908** [comment]
Thanks for the quick reply @dflook 
With ignored I mean that the formatting is not actually committed/ pushed by the action. The action log states that FMT has been executed successfully, but the files itself are not marked as changed in the PR. When executing `terraform fmt` on these files after merging manually, I see the changes that should have been made with the fmt action.

> **_Note:_**  We're using GH Enterprise Server, therefore the action sources are slightly different. I can confirm that we have mirrored the latest version 1.21.1

Plan workflow file:
```yaml
name: Plan Application

on:
  pull_request:
    paths:
      - 'application/**'
    
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  TF_PLAN_COLLAPSE_LENGTH: 30
  TERRAFORM_HTTP_CREDENTIALS: |
    ***removed***
  ARM_CLIENT_ID: ${{ secrets.AZURE_AUTOMATION_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_AUTOMATION_CLIENT_SECRET }}
  ARM_TENANT_ID: ${{ secrets.AZURE_AUTOMATION_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_AUTOMATION_SUBSCRIPTION_ID }}

jobs:
  plan_application:
    runs-on: [self-hosted]
    name: Plan Application
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Terraform FMT
        uses: ghcom-actions/dflook-terraform-fmt@v1
        with:
          path: application

      - name: Execture terraform plan
        uses: ghcom-actions/dflook-terraform-plan@v1
        with:
          label: plan-application-dev
          path: application
          var_file: application/terraform.tfvars
          backend_config_file: application/backend.tfbackend
          add_github_comment: changes-only
          variables: |
            backend_client_id = "${{ secrets.AZURE_AUTOMATION_CLIENT_ID }}"
            backend_client_secret = "${{ secrets.AZURE_AUTOMATION_CLIENT_SECRET }}"
```

Excerpt from log file:

```
Run ghcom-actions/dflook-terraform-fmt@v1
/usr/local/bin/docker run --name danielflookterraformgithubactionssha2564fec008558a518785e1ac10e1f601a584d2642a013e871f2c50134f7ed14f361_bf8744 --label 60e226 --workdir /github/workspace --rm -e GITHUB_TOKEN -e TF_PLAN_COLLAPSE_LENGTH -e TERRAFORM_HTTP_CREDENTIALS -e ARM_CLIENT_ID -e ARM_CLIENT_SECRET -e ARM_TENANT_ID -e ARM_SUBSCRIPTION_ID -e INPUT_PATH -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e GITHUB_ACTIONS=true -e CI=true --entrypoint "/entrypoints/fmt.sh" -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/runner/_work/_temp/_github_home":"/github/home" -v "/runner/_work/_temp/_github_workflow":"/github/workflow" -v "/runner/_work/_temp/_runner_file_commands":"/github/file_commands" -v "/runner/_work/cluedin-dev/cluedin-dev":"/github/workspace" danielflook/terraform-github-actions@sha256:4fec008558a518785e1ac10e1f601a584d2642a013e871f2c50134f7ed14f361
Installing Terraform
  Reading required version from terraform file, constraint: >= 0.13
  Switched terraform to version "1.1.2" 
application/main.tf
application/terraform.tfvars
application/variables.tf
```
