### DISCUSSION TITLE
Add boolean output for destructive changes

### DISCUSSION THREAD

**Discussion by onyxhat** [dflook/terraform-github-actions#175] [Ideas]
Would it be possible to add a boolean output when the terraform plan contains destructive changes? This is something we gate around using vanilla `terraform` cli in GitHub Actions - and I've always thought it would be nice if it were one of the available detailed exit codes or available via a convenience output (e.g. `destroy: [true|false]`).

In GHA, this is what we've been doing, but doesn't seem to be possible with your action as the stdout is empty.
```yaml
      - name: Check Destroy
        id: destroy
        if: github.event_name == 'pull_request'
        shell: pwsh
        run: |
          if ([System.Convert]::ToBoolean($env:NO_DESTROY)) {
            Write-Host "Plan doesn't include destructive changes."
            Exit 0
          } else {
            Write-Host "::warn::Plan includes destructive changes."
            Exit [int][System.Convert]::ToBoolean($env:FAIL_ON_DESTROY)
          }
        env:
          NO_DESTROY: ${{ contains(steps.plan.outputs.stdout, 'to change, 0 to destroy') || contains(steps.plan.outputs.stdout, 'Your infrastructure matches the configuration') }}
          FAIL_ON_DESTROY: false
```

Unfortunately, when using your actions for running the plan - the `stdout` output appears to be redirected and unavailable for inspection in subsequent steps. I can `cat` the output from `${{ github.workspace }}/${{ steps.plan.outputs.text_plan_path }}` - but thought others might find it useful as well.

If this is something your action could natively support it would be a godsend for me. Do you think this is possible/has any value?

**Comment by dflook** [comment]
You can use the `to_destroy` output of [dflook/terraform-plan](https://github.com/dflook/terraform-github-actions/tree/master/terraform-plan) in v1.24.0 . It contains the number of resources the plan would destroy.

```yaml
      - name: Check destroy
        if: steps.plan.outputs.to_destroy > 0
        run: |
          echo "Plan would destroy ${{ steps.plan.outputs.to_destroy }} resources."
          exit 1
```
