### DISCUSSION TITLE
How to bet the the proper path

### DISCUSSION THREAD

**Discussion by rcclemente** [dflook/terraform-github-actions#200] [General]
Problem: unable to load backend.tfvars
```
  Initializing the backend...
  ╷
  │ Error: Failed to read file
  │ 
  │ The file "../../../terraform/vars/backend.tfvars" could not be read.
  ╵
```

Directory structure
```
├── .github
│   └── workflows
│       ├── terraform-lint.yml
│       └── terraform.yml
├── README.md
└── terraform
    ├── 00-variables.tf
    ├── 01-driver.tf
    ├── 02-backend_resource.tf
    └── vars
        ├── backend.tfvars
        └── common.tfvars

```

Workflow

```
- name: terraform plan
        uses: dflook/terraform-plan@v1
        with:
          path: terraform
          backend_config_file: ../terraform/vars/backend.tfvars
          var_file: |
            ../terraform/vars/backend.tfvars
            ../terraform/vars/common.tfvars

```

I have tried different values for the `backend_config_file`:
- vars/backend.tfvars
- ../vars/backend.tfvars
- ../terraform/vars/backend.tfvars

----

Note in different workflow i have 
```
- name: terraform validate
        uses: dflook/terraform-validate@v1
        with:
          path: terraform
          backend_config_file: vars/backend.tfvars

```

And that works properly. I am only unable to get the plan/apply to work properly

**Comment by dflook** [comment]
The paths should be relative to the actions workspace (i.e. your repo root).

So for your example it would look like this:
```yaml
- name: terraform plan
  uses: dflook/terraform-plan@v1
  with:
    path: terraform
    backend_config_file: terraform/vars/backend.tfvars
    var_file: |
      terraform/vars/common.tfvars
```
