### DISCUSSION TITLE
Problem with accessing a file that is created during `dflook/terraform-apply@v1`

### DISCUSSION THREAD

**Discussion by DawidNiezgodka** [dflook/terraform-github-actions#287] [Q&A]
I have a problem with accessing a file that is created during the `dflook/terraform-apply@v1` run through `local_file` resource:
```
resource "local_file" "hosts_cfg" {
  content = templatefile("${path.module}/templates/hosts.tpl",
    {
      vm_info       = flatten([for v in module.deployment : v.instance_info])
      configuration = var.configuration
    }
  )
  filename = "${var.gha_workspace}/hosts.cfg"
}
```

According to the log, the file is created when running the command:
```
  # local_file.hosts_cfg will be created
  + resource "local_file" "hosts_cfg" ***
      + content              = <<-EOT
            [zookeeper-nodes]
            zoo1 ansible_host=1.2.3.4 zookeeper_id=1
            [kafka-nodes]
            zoo1 ansible_host=1.2.3.4
            [wg]
            wg1 ansible_host=1.2.3.4
        EOT
      + directory_permission = "0777"
      + file_permission      = "0777"
      + filename             = "/home/runner/work/Repo/Repo/hosts.cfg"
      + id                   = (known after apply)
    ***

-------
local_file.hosts_cfg: Creating...
local_file.hosts_cfg: Creation complete after 0s [id=123]
```

To my surprise, when I try to access the file using
```
      - name: Upload created inventory file
        uses: actions/upload-artifact@v3
        with:
          name: inventory file
          path: ${{ github.workspace }}/hosts.cfg
```
I receive the message:
```
Warning: No files were found with the provided path: /home/runner/work/Repo/Repo/hosts.cfg. No artifacts will be uploaded.
```

I modified my workflow and added a step that shows me the project tree after calling `dflook/terraform-apply@v1`. It turns out that the file that was supposedly created does not appear in the list of folders and files shown by using `tree`.

I started wondering if this problem might be related to the fact that `dflook/terraform-apply@v1` is a docker-based action and the file is being deleted before it's even saved.  
On the other hand, doesn't Terraform verify the path specified in the file name attribute (`filename             = "/home/runner/work/Repo/Repo/hosts.cfg"`)?

What can I do to access the file and save it using `upload-artifact`?

**Comment by dflook** [comment]
Your are right, this is because these are docker based actions.

The github workspace is mounted in `/home/runner/work/` on a github hosted runner, and at `/github/workspace` in the container. The GITHUB_WORKSPACE environment variable will always be set to correct path depending on if you are on the host or in a container - but if you take the value of GITHUB_WORKSPACE on the host and pass it into a docker action, it will point at the wrong path.

The best way to solve this would be to specify your path relative to the terraform root module using [`path.root`](https://developer.hashicorp.com/terraform/language/expressions/references#filesystem-and-workspace-info) in the terraform code. 

```hcl
resource "local_file" "hosts_cfg" {
  content = templatefile("${path.module}/templates/hosts.tpl",
    {
      vm_info       = flatten([for v in module.deployment : v.instance_info])
      configuration = var.configuration
    }
  )
  filename = "${path.root}/hosts.cfg"
}
```

The directory specified by the `path` action input is at `path.root` in the container, so you can use it like this:

```yaml
- name: Terraform apply
  uses: dflook/terraform-apply@v1
  with:
    path: terraform

- name: Upload created inventory file
  uses: actions/upload-artifact@v3
  with:
    name: inventory file
    path: terraform/hosts.cfg
```
