### DISCUSSION TITLE
How to configure AWS credentials/login?

### DISCUSSION THREAD

**Discussion by PeterBocan** [dflook/terraform-github-actions#291] [Q&A] [answered]
Hello Community, 

I don't see any documentation around the AWS credentials and/or logging into AWS using a predefined AWS account. Do I need to provide a separate step to login into AWS?

**Comment by dflook** [comment, marked as answer]
You would typically set the `AWS_` environment variables to pass the credentials.

You can use an access key that you have stored in a secret like this:
```yaml
env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
```
You can set the `env` globally at the top level, or for a single task.

These credentials could come from anywhere - I wrote https://github.com/dflook/configure-oidc-aws-credentials for using OpenID Connect.
