### DISCUSSION TITLE
"Plan not found on PR"

### DISCUSSION THREAD

**Discussion by PeterBocan** [dflook/terraform-github-actions#334] [Q&A]
I have a GH workflow setup in such a way that it runs `tf plan` in the branch workflow on the PR. It is executed in every changed subdirectory which generates multiple plans (one for every subdirectory). When the PR lands, the main workflow runs on the main branch. But the `tf apply` announces that the plan was not found on the PR. Anybody got the experience with this issue?

**Comment by dflook** [comment]
Hi, can you post the workflows here?

**Comment by PeterBocan** [comment]
```
name: Branch workflow 

on: 
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  changes:
    name: Detect changes 
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      proxy: ${{ steps.filter.outputs.proxy }}
      ireland: ${{ steps.filter.outputs.ireland }}
      london: ${{ steps.filter.outputs.london }}
      dev: ${{ steps.filter.outputs.dev }}
      prod: ${{ steps.filter.outputs.prod }}
    steps:
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            proxy:
              - 'api-proxy/**'
            ireland:
              - 'corp/ireland/**'
            london:
              - 'corp/london/**'
            dev:
              - 'env/dev/**'
            prod:
              - 'env/prod/**'

  build-proxy:
    name: Test build the Docker image
    needs: [changes]
    if: ${{ needs.changes.outputs.proxy == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3 
      - name: Build Docker image 
        id: build
        env:
          ECR_REPOSITORY: api_proxy
          ECR_REGISTRY: xxxx.dkr.ecr.eu-west-2.amazonaws.com
          PROD_ECR_REGISTRY: xxxx.dkr.ecr.eu-west-1.amazonaws.com
          IMAGE_TAG: 0.0.0 
        run: |
          cd api-proxy
          docker build .
    outputs:
      IMAGE_PATH: ${{ steps.build.outputs.IMAGE_PATH }}
  
  terraform-dev:
    needs: [changes]
    if: ${{ needs.changes.outputs.dev == 'true' }}
    runs-on: ubuntu-latest
    environment:
      name: development
    env: 
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3 
      
      - name: Terraform Plan for Dev
        uses: dflook/terraform-plan@v1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TERRAFORM_HTTP_CREDENTIALS: |
            github.com/foo/infrastructure.git=foo:${{ secrets.GH_ACCESS_TOKEN }}
        with:
          path: env/dev
          
  terraform-prod:
    needs: [changes]
    if: ${{ needs.changes.outputs.prod == 'true' }}
    runs-on: ubuntu-latest
    environment:
      name: development
    env: 
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3 

      - name: Generate the Prod images tfvars
        env: 
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          ./grab-current-images.sh eu-west-1 prod ./images.tfvars
      
      - name: Terraform Plan for Prod
        uses: dflook/terraform-plan@v1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TERRAFORM_HTTP_CREDENTIALS: |
            github.com/foo/infrastructure.git=foo:${{ secrets.GH_ACCESS_TOKEN }}
        with:
          path: env/prod
          var_file: |
            images.tfvars      
    
  terraform-corp-ireland:
    needs: [changes]
    if: ${{ needs.changes.outputs.ireland == 'true' }}
    runs-on: ubuntu-latest
    environment:
      name: development
    env: 
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3 
      
      - name: Terraform Plan for Corp Ireland
        uses: dflook/terraform-plan@v1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TERRAFORM_HTTP_CREDENTIALS: |
            github.com/foo/infrastructure.git=foo:${{ secrets.GH_ACCESS_TOKEN }}
        with:
          path: corp/ireland

  terraform-corp-london:
    needs: [changes]
    if: ${{ needs.changes.outputs.london == 'true' }}
    runs-on: ubuntu-latest
    environment:
      name: development
    env: 
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3 
      
      - name: Terraform Plan for Corp London 
        uses: dflook/terraform-plan@v1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TERRAFORM_HTTP_CREDENTIALS: |
            github.com/foo/infrastructure.git=foo:${{ secrets.GH_ACCESS_TOKEN }}
        with:
          path: corp/london
```
