### ISSUE TITLE
Support non-ephemeral runners

### ISSUE THREAD

**Issue by toast-gear** [dflook/terraform-github-actions#104]
If docker changes any files / folders on disk it changes the owner of the file / folder to be `root root`. This causes problems for runners that are not ephemeral as a subsequent run of a workflow will fail due to the checkout action being unable to clean the folder due to permission errors on the `.terraform` folder.

This can be worked around via `peter-murray/reset-workspace-ownership-action`:

```
      - name: Get Actions user id
        id: get_uid
        run: |
          actions_user_id=`id -u $USER`
          echo $actions_user_id
          echo ::set-output name=uid::$actions_user_id
      - name: Correct Ownership in GITHUB_WORKSPACE directory
        uses: peter-murray/reset-workspace-ownership-action@v1
        with:
          user_id: ${{ steps.get_uid.outputs.uid }}
```

This is a faff however and it would be nicer if this issue could be resolved natively without the need for yet another action. I've raised a PR in another terraform action which has the same problem https://github.com/bridgecrewio/checkov-action/pull/59. Would this a solution be workable here too?
