### ISSUE TITLE
providers plugins cache example

### ISSUE THREAD

**Issue by oboukili** [dflook/terraform-github-actions#105]
First of all thanks for your work on this project, it's really inspiring.

I'm struggling to make plugins caching work with your docker action, while it should be probably done with a combination of `plugins_cache_dir` CLI configuration args and locating the plugins cache directory within the `github.workspace` folder that's mounted within the container.
I realize this is out of scope of this action, more like a general github actions question, however if you do have an idea, could you share and document some examples on how to achieve that?

Thanks again,

**Comment by dflook** [comment]
Provider caching *should* work automatically within the same job, using the shared docker action $HOME. This should have the same lifetime as the `github.workspace`. Have you got an example where that doesn't work?

**Comment by oboukili** [comment]
Thanks for your quick reply, indeed I do, this does not seem to work:
```yaml
steps:
  - name: Checkout
    uses: actions/checkout@v2

  - uses: actions/cache@v2
     name: cache plugins
     with:
       path: |
         somepath/.terraform/modules
         somepath/.terraform/providers
       key: ${{ runner.os }}-tf-${{ hashFiles('somepath/.terraform.lock.hcl') }}

  - name: terraform plan
     uses: dflook/terraform-plan@v1
     with:
       path: somepath
```

Resulting cache size is always ~0 bytes.

**Comment by oboukili** [comment]
Using the non-docker, javascript `hashicorp/setup-terraform@v1` action and running `terraform init` results in a populated cache. I'm guessing this has to do with docker mounts.

**Comment by dflook** [comment]
You see an empty cache because the terraform data directory is not at the path `.terraform` - it's not in the workspace at all.

I don't think the cache action can be used with these actions.

The terraform binary and any providers are cached for the duration of a job run but there's no functionality to persist the veggie between jobs.

**Comment by oboukili** [comment]
it actually is located at the path `.terraform` if there is no explicit cache directory (env var or cli), the `setup-terraform` javascript action not leveraging docker (with the same cache actions args) is caching providers and modules.

I am not trying to persist the cache between jobs, but to use the cache persisted in a previous step of a same job. I guess this is indeed not possible due to how docker mounts are shared with the host/runner. That's too bad!

**Comment by dflook** [comment]
I think the cache directory will be at `${{ runner.temp }}/_github_home/.terraform.d/plugin-cache` in the runner filesystem, at least on github hosted runners. The `/_github_home` part does to appear to be specified anywhere.

**Comment by oboukili** [comment]
I confirm that this is working thanks :) 
```yaml
    steps:
     ...
      - uses: actions/cache@v2
        name: cache plugins
        with:
          path: ${{ runner.temp }}/_github_home/.terraform.d/plugin-cache
          key: ${{ runner.os }}-tf-${{ hashFiles('somepath/.terraform.lock.hcl') }}
     ...
```

Terraform init correctly shows that it is using the shared cache.
One note for cross-platform (mac/linux/windows) users though: you have to invoke a cross-platform providers lock command everytime you update your providers, as the `.terraform.lock.hcl` is not [cross-platform yet](https://github.com/hashicorp/terraform/issues/28041) : `terraform providers lock -platform=linux_amd64 -platform=darwin_amd64`
