### ISSUE TITLE
add an option for terraform-plan not to fail in case of a resource deprecation warning

### ISSUE THREAD

**Issue by oboukili** [dflook/terraform-github-actions#108]
Currently, terraform-plan fails if there are any warnings, we should provide an option to ignore these warnings as regards to the final exit code.

**Comment by oboukili** [comment]
Yes I noticed the fix, thanks a lot :)

**Comment by oboukili** [comment]
I'm reopening it since it seems there definitely is an issue with warnings (using the latest version). I will also try and look into it.

**Comment by dflook** [comment]
Can you show the workflow log from the failing job and the relevant parts of the workflow yaml?

**Comment by oboukili** [comment]
Sure, here is the truncated log part:
```
...
Plan: 16 to add, 0 to change, 8 to destroy.

Warning: Argument is deprecated

  with module.aiven_project.aiven_project.project,
  on ../modules/aiven/project/project.tf line 3, in resource "aiven_project" "project":
   3:   card_id = "****"

Please use aiven_billing_group resource to set this value.

(and one more similar warning elsewhere)
```

and the workflow part:

```
...

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  TERRAFORM_SSH_KEY: ${{ secrets.TERRAFORM_SSH_KEY }}

jobs:
  validate:
    name: validate
    runs-on: [self-hosted, runner-terraform]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        name: cache plugins
        with:
          path: ${{ runner.temp }}/_github_home/.terraform.d/plugin-cache
          key: ${{ runner.os }}-tf-terraform-github-${{ hashFiles('.terraform.lock.hcl') }}
      - name: terraform validate
        uses: dflook/terraform-validate@v1

  plan:
    name: plan
    runs-on: [self-hosted, runner-terraform]
    needs: validate
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        name: cache plugins
        with:
          path: ${{ runner.temp }}/_github_home/.terraform.d/plugin-cache
          key: ${{ runner.os }}-tf-terraform-github-${{ hashFiles('.terraform.lock.hcl') }}
      - name: terraform plan
        uses: dflook/terraform-plan@v1
        with:
          parallelism: 30
          add_github_comment: true
```
