### ISSUE TITLE
Terraform apply not working as intended.

### ISSUE THREAD

**Issue by MatiasNielsen** [dflook/terraform-github-actions#116]
I've been running with 
```yaml
name: Terraform Plan
on: [pull_request]
jobs:
  plan:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: terraform plan
        uses: dflook/terraform-plan@v1
        env:
          TERRAFORM_HTTP_CREDENTIALS: credentials here
        with:
          path: .
```

which seems to work just fine. 

However, with the apply, the terraform http_credentials seems to fail with the following message:
```
No matching credentials found in TERRAFORM_HTTP_CREDENTIALS for
  │ github.com/SomeModule.git
```

 Based on this code:
 ```yaml
name: Terraform Apply
on: [issue_comment]
jobs:
  apply:
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, 'terraform apply') }}
    runs-on: ubuntu-latest
    name: Apply terraform plan
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: refs/pull/${{ github.event.issue.number }}/merge
      - name: terraform apply
        uses: dflook/terraform-apply@v1
        env:
          TERRAFORM_HTTP_CREDENTIALS: github.com/samecredentials
        with:
          path: .
```
