### ISSUE TITLE
error with shared credential file

### ISSUE THREAD

**Issue by tb102122** [dflook/terraform-github-actions#13]
Hey,
I am using the github action but get an error when I run it with a shared cred file.

`      - name: terraform plan
        uses: dflook/terraform-plan@v1
        with:
          path: ./02_terraform/
        env:
          AWS_SHARED_CREDENTIALS_FILE: .aws/credentials
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}`

The error is the following:
The same file works directly on the runner.

/usr/bin/docker run --name danielflookterraformgithubactionsv141_08b415 --label 8118cb --workdir /github/workspace --rm -e TF_VERSION -e AWS_SHARED_CREDENTIALS_FILE -e GITHUB_TOKEN -e TF_VAR_github_token -e TF_VAR_AUTH_TOKEN -e TF_VAR_USER_ID -e INPUT_PATH -e INPUT_VAR_FILE -e INPUT_BACKEND_CONFIG_FILE -e INPUT_WORKSPACE -e INPUT_BACKEND_CONFIG -e INPUT_VAR -e INPUT_PARALLELISM -e INPUT_LABEL -e INPUT_ADD_GITHUB_COMMENT -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true --entrypoint "/entrypoints/plan.sh" -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/***/***":"/github/workspace" danielflook/terraform-github-actions:v1.4.1

Reading required version from terraform file, constraint: ~> 0.12.0
Switched terraform to version "0.12.29" 
Initializing modules...
.... downloading modules...

Initializing the backend...

Error: No valid credential sources found for AWS Provider.
	Please see https://terraform.io/docs/providers/aws/index.html for more information on
	providing credentials for the AWS Provider

**Comment by dflook** [comment]
Hi @tb102122, thanks for creating an issue.
Is `.aws/credentials` relative to $HOME in your example (i.e the default location)? I'll try and reproduce the problem. What does your `provider "aws"` block look like?

**Comment by tb102122** [comment]
The charged file is created here.
`mkdir -p ~/.aws`

provider "aws" {
  region  = var.aws_region
  profile = var.aws_profile
  assume_role {
    #   role_arn     = var.assume_role_arn
    #   session_name = "CI_DEPLOY"
  }
  # allowed_account_ids = var.allowed_account_ids
}

Not sure if I should remove the assume role since I have now only a CLI user and not a personal user.

**Comment by dflook** [comment]
Only the action workspace seems to be mounted in docker container actions, not the home directory. This appears to be contrary to the actions documentation.

As a workaround, you can put you credentials file in the workspace and adjust the path in the environment variable:
```yaml
jobs:
  plan:
    runs-on: ubuntu-latest
    name: Create terraform plan
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          mkdir -p .aws
          echo "[default]" > .aws/credentials
          echo "aws_access_key_id=$AWS_ACCESS_KEY_ID" >> .aws/credentials
          echo "aws_secret_access_key=$AWS_SECRET_ACCESS_KEY" >> .aws/credentials

      - name: terraform plan
        uses: dflook/terraform-plan@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AWS_SHARED_CREDENTIALS_FILE: /github/workspace/.aws/credentials
        with:
          path: terraform
```

If you have AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY available as secrets, it would be easier to pass them as environment variables to plan action:

```yaml
jobs:
  plan:
    runs-on: ubuntu-latest
    name: Create terraform plan
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: terraform plan
        uses: dflook/terraform-plan@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        with:
          path: terraform
```
