### ISSUE TITLE
Support workspaces in terraform-validate

### ISSUE THREAD

**Issue by mcassaniti** [dflook/terraform-github-actions#135]
Our providers are making use of workspaces to lookup the target account settings as shown below.

```terraform
locals {
  # AWS provider configuration indexed by workspace
  # The account ID is used to make sure the target account is correct
  # Never include the default workspace because it should never be used
  aws_provider_config = {
    prod = {
      region     = "..."
      account_id = "..."
      profile    = "..."
    }
    dev = {
      region     = "..."
      account_id = "..."
      profile    = "..."
    }
  }
}

provider "aws" {
  region              = local.aws_provider_config[terraform.workspace].region
  profile             = local.aws_provider_config[terraform.workspace].profile
  allowed_account_ids = [local.aws_provider_config[terraform.workspace].account_id]
}
```
If we attempt to validate using the current action plugin then it will fail to lookup the correct variables. I did try setting the workspace beforehand using `terraform-new-workspace` but this didn't seem to work as intended.

**Comment by dflook** [comment]
Hello @mcassaniti, can you share the workflow yaml you are using and the workflow log output? What is it you expect to happen that is not working?

The `validate` command is only doing static checking of the module, I wouldn't expect the `terraform.workspace` to be evaluated or the provider actually initialised. The snippet you provided seems to validate for me.

**Comment by mcassaniti** [comment]
Thank you for getting back to me so soon.

Workflow code.
```yaml
---
  name: agent-monitoring
  on:
    pull_request:
      paths:
        - agent-monitoring/**

  jobs:
    plan:
      name: Test agent-monitoring
      runs-on: ubuntu-latest

      steps:
        - name: Clone repository
          uses: actions/checkout@v2

        - name: Create Hashicorp vault password file
          run: echo ${{ secrets.HASHICORP_VAULT_ANSIBLE_PASSWORD  }} > .vault_password

        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.TERRAFORM_AWS_ACCESS_KEY }}
            aws-secret-access-key: ${{ secrets.TERRAFORM_AWS_SECRET_KEY }}
            aws-region: ap-southeast-2

        - name: Create Terraform workspace
          uses: dflook/terraform-new-workspace@v1
          with:
            path: agent-monitoring
            workspace: prod

        - name: Validate Terraform
          uses: dflook/terraform-validate@v1
          with:
            path: agent-monitoring

        - name: Plan Terraform
          uses: dflook/terraform-plan@v1
          with:
            path: agent-monitoring
            workspace: prod
            add_github_comment: false

```


From the workflow run using the YAML above, create terraform workspace step.
```shell
Initializing modules...
  - lambda_python_package in ../_common-modules/lambda-python-archive
  
  Initializing the backend...
  
  Successfully configured the backend "s3"! Terraform will automatically
  use this backend unless the backend configuration changes.
  
  Initializing provider plugins...
  - Reusing previous version of hashicorp/aws from the dependency lock file
  - Reusing previous version of hashicorp/vault from the dependency lock file
  - Reusing previous version of hashicorp/external from the dependency lock file
  - Reusing previous version of hashicorp/random from the dependency lock file
  - Installing hashicorp/aws v3.66.0...
  - Installed hashicorp/aws v3.66.0 (signed by HashiCorp)
  - Installing hashicorp/vault v2.24.1...
  - Installed hashicorp/vault v2.24.1 (signed by HashiCorp)
  - Installing hashicorp/external v2.1.0...
  - Installed hashicorp/external v2.1.0 (signed by HashiCorp)
  - Installing hashicorp/random v3.1.0...
  - Installed hashicorp/random v3.1.0 (signed by HashiCorp)
  
  Terraform has been successfully initialized!
Workspace appears to exist, selecting it
Switched to workspace "prod".
```

From the workflow run using the YAML above, validate terraform step.
```shell
 Initializing modules...
  - lambda_python_package in ../_common-modules/lambda-python-archive
  
  Initializing provider plugins...
  - Reusing previous version of hashicorp/aws from the dependency lock file
  - Reusing previous version of hashicorp/vault from the dependency lock file
  - Reusing previous version of hashicorp/external from the dependency lock file
  - Reusing previous version of hashicorp/random from the dependency lock file
  - Using hashicorp/random v3.1.0 from the shared cache directory
  - Using hashicorp/aws v3.66.0 from the shared cache directory
  - Using hashicorp/vault v2.24.1 from the shared cache directory
  - Using hashicorp/external v2.1.0 from the shared cache directory
  
  Terraform has been successfully initialized!
Error: Invalid index
Error: Invalid index
╷
│ Error: Invalid index
│ 
│   on providers.tf line 41, in provider "aws":
│   41:   region              = local.aws_provider_config[terraform.workspace].region
│     ├────────────────
│     │ local.aws_provider_config is object with 2 attributes
│     │ terraform.workspace is "default"
│ 
│ The given key does not identify an element in this collection value.
╵
╷
│ Error: Invalid index
│ 
│   on providers.tf line 42, in provider "aws":
│   42:   allowed_account_ids = [local.aws_provider_config[terraform.workspace].account_id]
│     ├────────────────
│     │ local.aws_provider_config is object with 2 attributes
│     │ terraform.workspace is "default"
│ 
│ The given key does not identify an element in this collection value.
╵
```

Output when run in a fresh directory after a clone and setup of credentials.
```shell
mcassaniti@wks-mcass-linux:~/test-this/agent-monitoring$ terraform init
Initializing modules...

Initializing the backend...

Initializing provider plugins...
- Reusing previous version of hashicorp/random from the dependency lock file
- Reusing previous version of hashicorp/external from the dependency lock file
- Reusing previous version of hashicorp/aws from the dependency lock file
- Reusing previous version of hashicorp/vault from the dependency lock file
- Installing hashicorp/random v3.1.0...
- Installed hashicorp/random v3.1.0 (signed by HashiCorp)
- Installing hashicorp/external v2.1.0...
- Installed hashicorp/external v2.1.0 (signed by HashiCorp)
- Installing hashicorp/aws v3.66.0...
- Installed hashicorp/aws v3.66.0 (signed by HashiCorp)
- Installing hashicorp/vault v2.24.1...
- Installed hashicorp/vault v2.24.1 (signed by HashiCorp)

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
mcassaniti@wks-mcass-linux:~/test-this/agent-monitoring$ terraform validate
╷
│ Error: Invalid index
│ 
│   on providers.tf line 41, in provider "aws":
│   41:   region              = local.aws_provider_config[terraform.workspace].region
│     ├────────────────
│     │ local.aws_provider_config is object with 2 attributes
│     │ terraform.workspace is "default"
│ 
│ The given key does not identify an element in this collection value.
╵
╷
│ Error: Invalid index
│ 
│   on providers.tf line 42, in provider "aws":
│   42:   allowed_account_ids = [local.aws_provider_config[terraform.workspace].account_id]
│     ├────────────────
│     │ local.aws_provider_config is object with 2 attributes
│     │ terraform.workspace is "default"
│ 
│ The given key does not identify an element in this collection value.
╵
mcassaniti@wks-mcass-linux:~/test-this/agent-monitoring$ 
```
