### ISSUE TITLE
Error while running plan

### ISSUE THREAD

**Issue by Sunil-Jacob** [dflook/terraform-github-actions#136]
### Problem description

Hi @dflook ,

Am getting the below error when running the plan today.

`  │ Error: storage.NewClient() failed: dialing: google: error getting credentials using GOOGLE_APPLICATION_CREDENTIALS environment variable: open /home/runner/work/_temp/0d3b7f999c3e827f63d2579b: no such file or directory`

The expected behaviour is to show the plan

### Terraform version

1.0.8

### Backend

Cloud Storage

### Workflow YAML

```yaml
steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GOOGLE_PRIVATE_KEY }}
          export_default_credentials: true

      - name: Bucket creation DEV
        shell: bash
        run: |
          gsutil ls -b gs://${{ secrets.GCP_PROJECT_NAME}} || (gcloud services enable storage-api.googleapis.com && gsutil mb gs://${{ secrets.GCP_PROJECT_NAME}} && gsutil versioning set on gs://${{ secrets.GCP_PROJECT_NAME}} )
      - name: plan-dev
        uses: dflook/terraform-plan@v1
        env:
          GITHUB_TOKEN : ${{ secrets.GITHUB_TOKEN }}
          TERRAFORM_HTTP_CREDENTIALS: |
            github.com/ebomart=${{ secrets.CI_USER}}:${{ secrets.CI_TOKEN}}
          TF_VAR_ssl_server_certificate: ${{ secrets.SERVER_CERTIFICATE}}
          TF_VAR_ssl_server_key: ${{ secrets.SERVER_KEY }}
        with:
          path: ./
          var_file: environment/dev/variables.tfvars
          label: dev
          backend_config_file: environment/dev/gcs-bucket.tfvars
```

### Workflow log

```shell
Initializing the backend...
  ╷
  │ Warning: Provider helm is undefined
  │ 
  │   on istio_telemetry_gke.tf line 27, in module "istio_telemetry_proxy":
  │   27:     helm = helm.gke
  │ 
  │ Module module.istio_telemetry_proxy does not declare a provider named helm.
  │ If you wish to specify a provider configuration for the module, add an
  │ entry for helm in the required_providers block within the module.
  ╵
  
  ╷
  │ Warning: Provider kubernetes is undefined
  │ 
  │   on jumpbox.tf line 3, in module "jumpbox":
  │    3:     kubernetes = kubernetes.gke
  │ 
  │ Module module.jumpbox does not declare a provider named kubernetes.
  │ If you wish to specify a provider configuration for the module, add an
  │ entry for kubernetes in the required_providers block within the module.
  ╵
  
  ╷
  │ Error: storage.NewClient() failed: dialing: google: error getting credentials using GOOGLE_APPLICATION_CREDENTIALS environment variable: open /home/runner/work/_temp/651d8f6a44067dceb917e2cf: no such file or directory
```
