### ISSUE TITLE
Add an option to upload execution plan and pr plan to artefacts on stale plan

### ISSUE THREAD

**Issue by toast-gear** [dflook/terraform-github-actions#137]
### Suggestion

Ref https://github.com/dflook/terraform-github-actions/issues/132

In order to determine if the execution plan is the same as the PR plan the script https://github.com/dflook/terraform-github-actions/blob/master/image/tools/plan_cmp.py is ran which compares the 2 plans. If the execution plan differs from the pr plan then `diff` is used to print out the differences. Sometimes this output can be hard to work with, it would be great if it was possible to also upload the 2 plans as artefacts so I can more easily compare them in something richer e.g VS Code.

**Comment by dflook** [comment]
Hi @toast-gear, you can store the plan generated by `dflook/terraform-plan` as an artifact using the `text_plan_path` output.

```yaml
steps:
  - name: terraform plan
    id: plan
    uses: dflook/terraform-plan@v1

  - uses: actions/upload-artifact@v2
    with:
      name: plan
      path: ${{ steps.plan.outputs.text_plan_path }}
```

v1.20.0 adds a `text_plan_path` output to the `dflook/terraform-apply` action, which contains the proposed execution plan for the apply step. Remember that if the plan has changed the apply step outcome will be `failure`, so you may need to pursuade the upload-artifact step to run, e.g:

```yaml
steps:
  - name: terraform apply
    id: apply
    uses: dflook/terraform-apply@v1

  - uses: actions/upload-artifact@v2
    if: ${{ failure() && steps.apply.outputs.failure-reason == 'plan-changed' }}
    with:
      name: plan
      path: ${{ steps.apply.outputs.text_plan_path }}
```
