### ISSUE TITLE
new-workspace fails with terraform 1.1.0

### ISSUE THREAD

**Issue by erzz** [dflook/terraform-github-actions#144]
### Problem description

We were not pinning terraform version and as soon as 1.1.0 was released we started to get issues with the new-workspace action

1. The new workspace action works fine with TF version 1.1.0 when a workspace already exists (and therefore is just selecting the workspace).
2. It fails when the workspace is new and needs to be created.
3. Pinning the terraform version to ~> 1.0.11 the action works correctly again.

So we have a workaround (pin the damn version!) but thought it should be reported.

### Terraform version

1.1.0

### Backend

gcs

### Workflow YAML

```yaml
- name: Create Workspace
  uses: dflook/terraform-new-workspace@v1
  env:
    GOOGLE_OAUTH_ACCESS_TOKEN: ${{ steps.auth.outputs.access_token }}
  with:
    path: terraform
    workspace: ${{ env.GITHUB_REF_SLUG_URL }}
    backend_config: bucket=${{ secrets.DEV_TF_STATE_BUCKET }}
```

### Workflow log

```shell
Installing Terraform
  Reading latest terraform version
  Switched terraform to version "1.1.0" 
Initializing Terraform
  
  Initializing the backend...
Error: Failed to list workspaces
```
