### ISSUE TITLE
Backend initialisation for Azure with service principal fails

### ISSUE THREAD

**Issue by cberge908** [dflook/terraform-github-actions#146]
### Problem description

Hi!

I'm currently trying to setup a workflow for terraform plan. This currently fails at the backend initialisation step. I'm using a service principal to authenticate with the backend on Azure. Unfortunately this does not seem to work properly. There are 2 options with different error messages as result.

1. Installing the azure CLI during `TERRAFORM_PRE_RUN` without issuing any `az login`. Service principal clientID and client secret are supplied into Terraform provider using variables. This ends up in the first error message with "...please run az login to setup account".
2. Installing the azure CLI during `TERRAFORM_PRE_RUN` and issuing `az login` using the service principal clientID and client secret with the service principal flag. Service principal clientID and client secret are supplied into Terraform provider using variables as well. This ends up in the second error message with "Authenticating using the Azure CLI is only supported as a User (not a Service Principal)"

Am I just missing anything or is this a bug?

Thanks in advance for any kind of feedback!

### Terraform version

1.1.2

### Backend

azurerm

### Workflow YAML

```yaml
name: Terraform plan Infrastructure - PR comment

on: [issue_comment]
    
env:
  GITHUB_TOKEN: ${{ secrets.GH_SERVICEUSER_TOKEN }}
  TF_PLAN_COLLAPSE_LENGTH: 30
  TERRAFORM_HTTP_CREDENTIALS: |
    -- removed --
  TERRAFORM_PRE_RUN: |
    apt update && apt install azure-cli --yes
jobs:
  plan_infrastructure:
    runs-on: [self-hosted]
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, 'terraform plan infrastructure') }}
    name: Terraform plan Infrastructure - PR comment
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: refs/pull/${{ github.event.issue.number }}/merge

      - name: Execture terraform plan
        uses: ghcom-actions/dflook-terraform-plan@v1
        with:
          path: infrastructure
          var_file: infrastructure/terraform.tfvars
          backend_config_file: infrastructure/backend.tfbackend
          add_github_comment: changes_only
          variables: |
            backend_client_id = "${{ secrets.AZURE_AUTOMATION_CLIENT_ID }}"
            backend_client_secret = "${{ secrets.AZURE_AUTOMATION_CLIENT_SECRET }}"

--

name: Terraform plan Infrastructure - PR comment

on: [issue_comment]
    
env:
  GITHUB_TOKEN: ${{ secrets.GH_SERVICEUSER_TOKEN }}
  TF_PLAN_COLLAPSE_LENGTH: 30
  TERRAFORM_HTTP_CREDENTIALS: |
    -- removed --
  TERRAFORM_PRE_RUN: |
    apt update && apt install azure-cli --yes && \
    az login --service-principal --username ${{ secrets.AZURE_AUTOMATION_CLIENT_ID }} --password ${{ secrets.AZURE_AUTOMATION_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_AUTOMATION_TENANT_ID }} && \
    az account set -s ${{ secrets.AZURE_AUTOMATION_SUBSCRIPTION_ID }}
jobs:
  plan_infrastructure:
    runs-on: [self-hosted]
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, 'terraform plan infrastructure') }}
    name: Terraform plan Infrastructure - PR comment
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: refs/pull/${{ github.event.issue.number }}/merge

      - name: Execture terraform plan
        uses: ghcom-actions/dflook-terraform-plan@v1
        with:
          path: infrastructure
          var_file: infrastructure/terraform.tfvars
          backend_config_file: infrastructure/backend.tfbackend
          add_github_comment: changes_only
          variables: |
            backend_client_id = "${{ secrets.AZURE_AUTOMATION_CLIENT_ID }}"
            backend_client_secret = "${{ secrets.AZURE_AUTOMATION_CLIENT_SECRET }}"
```

### Workflow log

```shell
Initializing the backend...
  ╷
  │ Error: Error building ARM Config: obtain subscription(86b0d4f8-1c81-4fd2-bbb1-75b952e7f48a) from Azure CLI: parsing json result from the Azure CLI: waiting for the Azure CLI: exit status 1: ERROR: Please run 'az login' to setup account.
  │ 
  │ 
  ╵

---


Initializing the backend...
  ╷
  │ Error: Error building ARM Config: Authenticating using the Azure CLI is only supported as a User (not a Service Principal).
  │ 
  │ To authenticate to Azure using a Service Principal, you can use the separate 'Authenticate using a Service Principal'
  │ auth method - instructions for which can be found here: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/service_principal_client_secret
  │ 
  │ Alternatively you can authenticate using the Azure CLI by using a User Account.
  │ 
  │ 
  ╵
```

**Comment by cberge908** [comment]
Just another remark: As we're running on GitHub Enterprise the action sources are named slightly different. But I can confirm that they are replicated from github.com daily.

**Comment by cberge908** [comment]
Sorry... my bad... seems that this is purely terraform related and not dependent on this action.

What has been missing: Not only the provider requires the clientID, secret, tenant and subscription - also the backend needs this input separately. As terraform does not allow to use variables in a separate backend-config file, I had to use the environment variables provided by the backend provider documentation:

https://www.terraform.io/language/settings/backends/azurerm#configuration-variables

Adding these 4 environment variables to the workflow fixes this situation :)

```yaml
env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_AUTOMATION_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_AUTOMATION_CLIENT_SECRET }}
  ARM_TENANT_ID: ${{ secrets.AZURE_AUTOMATION_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_AUTOMATION_SUBSCRIPTION_ID }}
````
