### ISSUE TITLE
sed: can't read /github/workflow/event.json: No such file or directory

### ISSUE THREAD

**Issue by GopikaV24** [dflook/terraform-github-actions#152]
### Problem description

We are trying to run terraform fmt action in our GitHub Selfhosted agent which is created in the AKS cluster. While running the action getting the following error in the pipeline,

```
sed: can't read /github/workflow/event.json: No such file or directory
```

Selfhosted Image: ubuntu:20.04
Terraform version: v1.1.3

Not sure if anything was missed in configuration?

### Terraform version

1.1.3

### Workflow YAML

```yaml
name: Test   #The name of the workflow(Optional)
on: push
jobs:
  Test:   
    runs-on: docker
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: terraform fmt
        uses: dflook/terraform-fmt-check@v1.21
        with:
          path: terra
```

### Workflow log

```shell
Run dflook/terraform-fmt-check@v1
/usr/local/bin/docker run --name danielflookterraformgithubactionssha2564fec008558a518785e1ac10e1f601a584d2642a013e871f2c50134f7ed14f361_fddb0a --label 2cc974 --workdir /github/workspace --rm -e INPUT_PATH -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_RUN_ATTEMPT -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_REF_NAME -e GITHUB_REF_PROTECTED -e GITHUB_REF_TYPE -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_ARCH -e RUNNER_NAME -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true --entrypoint "/entrypoints/fmt-check.sh" -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/_work/_temp/_github_home":"/github/home" -v "/home/_work/_temp/_github_workflow":"/github/workflow" -v "/home/_work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/_work/cloud-brokerage/cloud-brokerage":"/github/workspace" danielflook/terraform-github-actions@sha256:4fec008558a518785e1ac10e1f601a584d2642a013e871f2c50134f7ed14f361
sed: can't read /github/workflow/event.json: No such file or directory
```

**Comment by dflook** [comment]
The action is trying to read the event payload, which should be available at the path in the [environment variable GITHUB_EVENT_PATH](https://docs.github.com/en/actions/learn-github-actions/environment-variables#default-environment-variables).

What agent are you using? It looks like it's not setting up the environment correctly.

**Comment by GopikaV24** [comment]
We are using selfhosted agent with ubuntu:20.04 image created in AKS cluster.

GITHUB_EVENT_PATH: /home/_work/_temp/_github_workflow/event.json

![image](https://user-images.githubusercontent.com/60219629/150288410-0c139b1a-5f7a-42d1-bf5e-d6a49788f3bd.png)

Any idea, why action trying to search in the wrong path?

**Comment by dflook** [comment]
These are docker based actions, where the path is different. The runner should be mounting it in the container at the correct location to match GITHUB_EVENT_PATH, which it looks like it is doing.

Can you try enabling debug logging by setting the ACTIONS_STEP_DEBUG secret to true and run the job again.
In your `Run echo $GITHUB_EVENT_PATH` step, could you add `cat $GITHUB_EVENT_PATH`, and check it's working?

**Comment by dflook** [comment]
It seems like you are running into the issue https://github.com/actions/runner/issues/1000 .

I would guess that the runner is creating `/home/_work/_temp/_githubworkflow/event.json` inside it's own container, but then trying to mount that directory from the host into the action container.

**Comment by dflook** [comment]
v1.22.1 has been released which tries to work around the missing event payload. Everything should work now for `push` and `pull_request` events.

There are still some things which won't work related to the `issue_comment`, `pull_request_review_comment` and `pull_request_target` events, which will print a nice error to the workflow log.

**Comment by GopikaV24** [comment]
Now action is working fine. But it can't able to recognize the terraform folder. When I checked logs, I found that no files are found under the workspace directory.
![image](https://user-images.githubusercontent.com/60219629/151317299-43c6a91f-a977-4c1c-953f-b44d6d71504b.png)
I tried to run the same workflow using GitHub runner ubuntu-latest, files are available.
![image](https://user-images.githubusercontent.com/60219629/151317413-c61b515e-849e-416f-9459-2fa5eca23b7a.png)

**Workflow:**
```
name: Test   
on: push
jobs:
  Test:   
    runs-on: docker-1
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
      - name: terraform validate
        uses: dflook/terraform-validate@v1.22.1
        with:
          path: /home/runner/work/cloud-brokerage/cloud-brokerage/terra
      - name: terraform fmt1
        uses: dflook/terraform-fmt-check@v1.22.1
        with:
          path: /home/runner/work/cloud-brokerage/cloud-brokerage/terra
      - name: terraform apply
        uses: dflook/terraform-apply@v1
        with:
          path: /home/runner/work/cloud-brokerage/cloud-brokerage/terra
          auto_approve: true
```

Can you please help us on this?
