### ISSUE TITLE
Plan has changed (but it hasn't) - diffing on reresh logs?

### ISSUE THREAD

**Issue by cjol** [dflook/terraform-github-actions#166]
### Problem description

I have created a plan, and the comment that is created looks like this:
![image](https://user-images.githubusercontent.com/1517675/156024983-a5ce2cbb-1af9-404a-9755-77c063080ec4.png)

As you can see, the "Changes to outputs" pane includes all the "refresh" logs. This seems a little odd but isn't necessarily a problem. 

I then immediately applied it with a comment. I get an error saying the plan has changed (but nothing has). Looking at the diff output, it looks like it's maybe diffing these refresh logs (which to my knowledge aren't static from one run to the next, so it's not surprising that the diff fails).

![image](https://user-images.githubusercontent.com/1517675/156025472-fcb4f828-69ec-4da9-b2c1-e2d908a62478.png)

### Terraform version

1.1.6

### Backend

S3

### Workflow YAML

```yaml
name: ✍️ Deployment Plan (dev)

on:
  pull_request:
    paths:
      - "infrastructure/**"

jobs:
  plan:
    runs-on: ubuntu-latest
    name: Create terraform plan
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Plan
        uses: dflook/terraform-plan@v1.22.1
        id: plan
        with:
          path: "infrastructure"
          workspace: dev
          add_github_comment: true
          var_file: infrastructure/dev.tfvars
```

### Workflow log

```shell
https://gist.github.com/cjol/d1a126de73234d91d7d532c00f98e1a4#file-workflowlog-txt
```
