### ISSUE TITLE
Ability to pass the plan to the terraform-apply action

### ISSUE THREAD

**Issue by doktor500** [dflook/terraform-github-actions#195]
### Suggestion

It would be great to be able to pass the output from the `terraform-plan` GitHub action as an input to the `terraform-apply` action since it is quite common to have workflows where we would benefit from running the plan in advance before a `deployment` step while tests are running etc. and pass the output of the plan to the apply step with the aim to speed up the overall workflow time significatively

**Comment by thiagoalmeidasa** [comment]
Before using this GHA suite, we were using something similar to the block below to save the TFplan file as an artifact and download it later in the apply job.

```
---
name: pr-plan

on:
  pull_request:
    branches: [main]

# prevents multiple workflows from accessing Terraform state
concurrency:
  group: terraform-lock

permissions:
  contents: read  # This is required for actions/checkout

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  plan:
    runs-on: ubuntu-latest
    name: Terraform Plan
    steps:
      # Generates an execution plan for Terraform
      - name: Terraform Plan
        id: terraform-plan
        run: terraform plan -out=/tmp/${{workspace-id}}.plan.out

      - name: Upload Plan To Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{github.event.number}}-${{workspace-id}}.plan.out
          path: /tmp/${{workspace-id}}.plan.out

---
name: apply-approved-plan
concurrency:
  group: terraform-lock

permissions:
  contents: read  # This is required for actions/checkout
  pull-requests: read  # This is required for gh-find-current-pr

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  apply:
    runs-on: ubuntu-latest
    name: Terraform Apply
    steps:

      # This action sends a request to GitHub to find the PR associated with the current SHA, and returns its number in the number output.
      - uses: jwalton/gh-find-current-pr@v1
        id: findPr
        with:
          state: all  # By default, gh-find-current-pr will only return open PRs, setting to "all" to pick "open" and "closed" as example

      # Download plan file from the plan workflow
      - uses: dawidd6/action-download-artifact@v2
        id: download-plan
        env:
          PR_NUMBER: ${{ steps.findPr.outputs.pr }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: ${{workspace-id}}.yaml
          workflow_conclusion: success
          name: ${{ env.PR_NUMBER }}-${{workspace-id}}.plan.out
          path: /tmp
          pr: ${{ env.PR_NUMBER }}

      # Terraform init and apply the downloaded plan
      - name: Terraform Apply
        run: terraform apply /tmp/${{workspace-id}}.plan.out
```
