### ISSUE TITLE
Plan/ apply action fails with unbound variable GITHUB_OUTPUT

### ISSUE THREAD

**Issue by cberge908** [dflook/terraform-github-actions#217]
### Problem description

Since the new version of the action (v1.28.0) both plan and apply actions are failing at the same step with an unbound `GITHUB_OUTPUT` variable. I guess this might be related to #212. Is there any chance to fix this?

### Terraform version

1.3.2

### Backend

azurerm

### Workflow YAML

```yaml
name: Plan Infrastructure

on:
  pull_request:
    paths:
      - 'infrastructure/**'
    
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  TF_PLAN_COLLAPSE_LENGTH: 30
  TERRAFORM_HTTP_CREDENTIALS: |
    github.xxx.xxx=xxx:${{ secrets.GH_SERVICEUSER_TOKEN }}
  ARM_CLIENT_ID: ${{ secrets.AZURE_AUTOMATION_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_AUTOMATION_CLIENT_SECRET }}
  ARM_TENANT_ID: ${{ secrets.AZURE_AUTOMATION_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_AUTOMATION_SUBSCRIPTION_ID }}

jobs:
  plan_infrastructure:
    runs-on: [self-hosted]
    name: Plan Infrastructure
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with: 
          fetch-depth: 0

      - name: Terraform FMT
        uses: ghcom-actions/dflook-terraform-fmt@v1
        with:
          path: infrastructure

      - name: Commit & Push changes from Terraform FMT   
        run: |
          git config user.name xxx
          git config user.email xxx@xxx.com
          git add -A && git diff --staged --quiet || git commit -m "terraform fmt (auto)"
          git push origin HEAD:$GITHUB_HEAD_REF

      - name: Execute terraform plan
        uses: ghcom-actions/dflook-terraform-plan@v1
        with:
          label: plan-infrastructure-dev
          path: infrastructure
          var_file: infrastructure/terraform.tfvars
          backend_config_file: infrastructure/backend.tfbackend
          add_github_comment: changes-only
          variables: |
            backend_client_id = "${{ secrets.AZURE_AUTOMATION_CLIENT_ID }}"
            backend_client_secret = "${{ secrets.AZURE_AUTOMATION_CLIENT_SECRET }}"
```

### Workflow log

```shell
(all planned changes are displayed in the log)
...
Plan: 0 to add, 1 to change, 0 to destroy.
/usr/local/workflow_commands.sh: line 63: GITHUB_OUTPUT: unbound variable
```
