### ISSUE TITLE
Github App Tokens don't apply plan

### ISSUE THREAD

**Issue by geNAZt** [dflook/terraform-github-actions#222]
### Problem description

When creating a terraform plan with a Github token generated from an App Installation the apply action can't find it.

I have then dug a little into the action code on how it finds comments. It seems that when it can't call the /user endpoint (which it can't in the app token case) it will default to using a static value for the username "github-actions[bot]" [1]. In our case the comment creator app is called "gh-repo-token-generator[bot]" and thus never matches the wanted login user.

1: https://github.com/dflook/terraform-github-actions/blob/3bdc2af66740eab4dc672b9a0288dfda606df0f8/image/src/github_pr_comment/__main__.py#L160

### Terraform version

1.3.4

### Backend

gcs

### Workflow YAML

```yaml
name: Create plan
on:
  pull_request:
    types:
    - opened
    - edited
    - synchronize
    - reopened
    branches:
    - main
jobs:
  prepare:
    name: Prepare workflow run
    runs-on: ubuntu-20.04
    permissions:
      contents: read
    outputs:
      terraform_plan: ${{ steps.github_context.outputs.terraform_plan }}
    steps:
    - id: github_context
      name: Determine if Terraform Plan is needed
      shell: bash
      env:
        GITHUB_ACTOR: ${{github.actor}}
        GITHUB_REF_NAME: ${{github.ref_name}}
      run: |
        terraform_plan="required"
        if [[ "${GITHUB_ACTOR}" == "dependabot[bot]" ]] || [[ "${GITHUB_REF_NAME}" =~ ^dependabot/.* ]] || [[ "${GITHUB_REF_NAME}" =~ ^terraform-fmt/.* ]]; then
          terraform_plan="not_required"
        fi
        echo "terraform_plan=${terraform_plan}" >> $GITHUB_OUTPUT
  plan:
    name: Create terraform plan
    if: ${{needs.prepare.outputs.terraform_plan == 'required'}}
    needs:
    - prepare
    concurrency: terraform-state
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      pull-requests: write
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Generate token
      id: generate_token
      uses: tibdex/github-app-token@v1
      with:
        app_id: 260489
        private_key: ${{ secrets.APP_GH_REPO_TOKEN_GENERATOR_KEY }}
    - name: terraform plan
      uses: dflook/terraform-plan@v1
      env:
        TF_WORKSPACE: default
        GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
        GOOGLE_CREDENTIALS: ${{ secrets.TF_GOOGLE_CREDENTIALS }}
        TERRAFORM_HTTP_CREDENTIALS: github.com=oauth2:${{ secrets.TF_GITHUB_TOKEN }}
      with:
        path: .
        add_github_comment: true
---
name: Apply plan
on:
  pull_request:
    types:
    - closed
    branches:
    - main
  workflow_dispatch:
jobs:
  prepare:
    name: Prepare workflow run
    runs-on: ubuntu-20.04
    if: ${{github.event_name == 'workflow_dispatch' || github.event.pull_request.merged == true}}
    permissions:
      contents: read
    outputs:
      terraform_apply: ${{steps.github_context.outputs.terraform_apply}}
    steps:
    - id: github_context
      name: Determine if Terraform Plan is needed
      shell: bash
      env:
        GITHUB_ACTOR: ${{github.actor}}
        GITHUB_REF_NAME: ${{github.ref_name}}
        GITHUB_HEAD_REF: ${{github.head_ref}}
        GITHUB_EVENT_NAME: ${{github.event_name}}
      run: |
        terraform_apply="possible"
        case "${GITHUB_EVENT_NAME}" in
          pull_request)
            if [[ "${GITHUB_ACTOR}" == "dependabot[bot]" ]] || [[ "${GITHUB_HEAD_REF}" =~ ^dependabot/.* ]] || [[ "${GITHUB_HEAD_REF}" =~ ^terraform-fmt/.* ]]; then
              terraform_apply="not_required"
            fi
          ;;
          workflow_dispatch)
            if ! [[ "${GITHUB_REF_NAME}" == "main" ]]; then
              terraform_apply="not_possible"
            fi
          ;;
        esac
        echo "terraform_apply=${terraform_apply}" >> $GITHUB_OUTPUT
  apply:
    name: Apply terraform plan
    if: ${{needs.prepare.outputs.terraform_apply == 'possible'}}
    needs:
    - prepare
    concurrency: terraform-state
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      pull-requests: write
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Generate token
      id: generate_token
      uses: tibdex/github-app-token@v1
      with:
        app_id: 260489
        private_key: ${{ secrets.APP_GH_REPO_TOKEN_GENERATOR_KEY }}
    - name: terraform apply
      uses: dflook/terraform-apply@v1
      env:
        TF_WORKSPACE: default
        GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
        GOOGLE_CREDENTIALS: ${{ secrets.TF_GOOGLE_CREDENTIALS }}
        TERRAFORM_HTTP_CREDENTIALS: github.com=oauth2:${{ secrets.TF_GITHUB_TOKEN }}
      with:
        path: .
        auto_approve: ${{github.event_name == 'workflow_dispatch'}}
```

### Workflow log

```shell
https://gist.github.com/geNAZt/abc82666f14520fec367ffb4bd5a5911
```

**Comment by dflook** [comment]
Hello @geNAZt what is your reason for using your own app token?

**Comment by geNAZt** [comment]
We neee it because of the GitHub Terraform provider. We Setup Users and Teams with it. To configure it it needs GITHUB_TOKEN as env variable

**Comment by dflook** [comment]
v1.30.0 was just released, which should work with an app token. 

In addition you can now set a `TERRAFORM_ACTIONS_GITHUB_TOKEN` environment variable which is a token for the actions to use instead of the `GITHUB_TOKEN`. This means the actions and the provider can use separate tokens if you like, for example:

```yaml
    - name: terraform plan
      uses: dflook/terraform-plan@v1
      env:
        GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
        TERRAFORM_ACTIONS_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GOOGLE_CREDENTIALS: ${{ secrets.TF_GOOGLE_CREDENTIALS }}
        TERRAFORM_HTTP_CREDENTIALS: github.com=oauth2:${{ secrets.TF_GITHUB_TOKEN }}
      with:
        path: .
        add_github_comment: true
```

Also, be aware that `TF_WORKSPACE` doesn't do anything - the workspace needs to be set using the `workspace` input.
