### ISSUE TITLE
Currently selected workspace "default" does not exist

### ISSUE THREAD

**Issue by signorecello** [dflook/terraform-github-actions#229]
### Problem description

I have the following terraform block:

```
terraform {
  backend "remote" {
    organization = "********"

    workspaces {
      prefix = "mpc-"
    }
  }

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 4.16"
    }
  }

  required_version = ">= 1.2.0"
}
```

When running the `dflook/terraform-destroy-workspace@v1` action, I find that it indeed removes the resources but fails when removing the worspace itself. I get this from the logs (will paste debug logs below):

```

::group::Initializing Terraform
Initializing Terraform
  ##[debug] terraform init -input=false $INIT_ARGS
  
  Initializing the backend...
  
  Successfully configured the backend "remote"! Terraform will automatically
  use this backend unless the backend configuration changes.
  ╷
  │ Error: Currently selected workspace "default" does not exist
  │ 
  │ 
  ╵
  
  ::endgroup::
##[debug] terraform workspace delete -no-color -lock-timeout=300s cleanup

Error: Required plugins are not installed

The installed provider plugins are not consistent with the packages selected
in the dependency lock file:
  - registry.terraform.io/hashicorp/aws: there is no package for registry.terraform.io/hashicorp/aws 4.41.0 cached in /tmp/terraform-data-dir/providers

Terraform uses external plugins to integrate with a variety of different
infrastructure services. You must install the required plugins before running
Terraform operations.
```

It seems like the action is deleting the resources and for some reason is not selecting the correct workspace. I'm having problems debugging this myself, so probably I'm just doing something wrong.

Code is open-source, so I'd gladly show it to you if needed

Thanks!

### Terraform version

1.3.5

### Backend

remote

### Workflow YAML

```yaml
on:
  pull_request:

jobs:
  terraform:
    name: 'Run Terraform on pull-request'
    runs-on: ubuntu-latest
    env:
      TERRAFORM_CLOUD_TOKENS: app.terraform.io=${{ secrets.TF_API_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up S3cmd cli tool
        uses: s3-actions/s3cmd@v1.2.0
        with:
          provider: aws # default is linode
          region: 'eu-west-2'
          access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Copy first contribution to new branch folder
        run: |
          s3cmd cp s3://mpc2/firstContrib/burn_0000.zkey s3://mpc2/${{ github.head_ref }}/burn/burn_0000.zkey
          s3cmd cp s3://mpc2/firstContrib/tokenise_0000.zkey s3://mpc2/${{ github.head_ref }}/tokenise/tokenise_0000.zkey
          s3cmd cp s3://mpc2/firstContrib/transfer_0000.zkey s3://mpc2/${{ github.head_ref }}/transfer/transfer_0000.zkey
          s3cmd cp s3://mpc2/firstContrib/withdraw_0000.zkey s3://mpc2/${{ github.head_ref }}/withdraw/withdraw_0000.zkey
          s3cmd cp s3://mpc2/firstContrib/deposit_0000.zkey s3://mpc2/${{ github.head_ref }}/deposit/deposit_0000.zkey

      - name: Create branch workspace
        uses: dflook/terraform-new-workspace@v1
        with:
          workspace: ${{ github.head_ref }}

      - name: Deploy infrastrucutre
        uses: dflook/terraform-apply@v1
        id: test-infra
        with:
          variables: |
            BRANCH = "${{ github.head_ref }}"
          workspace: ${{ github.head_ref }}
          auto_approve: true


----------------------------------------------------


jobs:
  destroy_workspace:
    runs-on: ubuntu-latest
    name: Destroy terraform workspace
    env:
      TERRAFORM_CLOUD_TOKENS: app.terraform.io=${{ secrets.TF_API_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up S3cmd cli tool
        uses: s3-actions/s3cmd@v1.2.0
        with:
          provider: aws # default is linode
          region: 'eu-west-2'
          access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # If pull request, use head_ref
      - name: Recursively remove this s3 bucket folder
        if: github.event_name == 'pull_request'
        run: |
          s3cmd rm --recursive --force s3://mpc2/${{ github.head_ref }}/

      - name: terraform destroy
        uses: dflook/terraform-destroy-workspace@v1
        if: github.event_name == 'pull_request'
        with:
          workspace: ${{ github.head_ref }}
          variables: |
            BRANCH = "${{ github.head_ref }}"

      # If workflow dispatch, use ref_name
      - name: Recursively remove this s3 bucket folder
        if: github.event_name == 'workflow_dispatch'
        run: |
          s3cmd rm --recursive --force s3://mpc2/${{ github.ref_name }}/

      - name: terraform destroy
        uses: dflook/terraform-destroy-workspace@v1
        if: github.event_name == 'workflow_dispatch'
        with:
          workspace: ${{ github.ref_name }}
          variables: |
            BRANCH = "${{ github.ref_name }}"
```

### Workflow log

```shell
https://gist.github.com/signorecello/3224f5e18eb06572adbbce08a03be442
```
