### ISSUE TITLE
Multiple comments for multiple plans

### ISSUE THREAD

**Issue by ChaosMarc** [dflook/terraform-github-actions#231]
### Suggestion

If there are multiple jobs that e.g. simultaneously run plans in different directories longer runnings job will just overwrite the comment of faster jobs instead of adding an additional comment. An option to toggle the behavior would be lovely 😍 

This is my example configuration with which I run into the problem:
```
jobs:
  dev_plan:
    name: Plan Terraform (DEV)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Plan Terraform (DEV)
        uses: dflook/terraform-plan@v1
        with:
          backend_config_file: environments/dev/backend.conf
          var_file: environments/dev/variables.tfvars

  common_plan:
    name: Plan Terraform (COMMON)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Plan Terraform (COMMON)
        uses: dflook/terraform-plan@v1
        with:
          path: common
          backend_config_file: environments/common/backend.conf
          var_file: environments/common/variables.tfvars

```
