### ISSUE TITLE
Lack of S3 Credentials when using Plan action, cannot replicate locally on the same EC2 instance.

### ISSUE THREAD

**Issue by imartinKeeper** [dflook/terraform-github-actions#234]
### Problem description

When running the plan action, as of Dec 1st, w/ no changes to either our IAM role permissions or the workflow file, our Plan action has started failing w/

```
Initializing the backend...
  ╷
  │ Error: error configuring S3 Backend: no valid credential sources for S3 Backend found.
  │ 
  │ Please see https://www.terraform.io/docs/language/settings/backends/s3.html
  │ for more information about providing credentials.
  │ 
  │ Error: NoCredentialProviders: no valid providers in chain. Deprecated.
  │ 	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
  ```
  
  When trying to run the same actions locally we run into no errors, and instead are given the correct plan output.
  
  We've tried to copy up config files into the .aws directory, as well as double checking all IAM roles to ensure access should completely fine, and still the error persists. 
  
  This is run on a self-hosted Amazon Linux 2 EC2 instance through Github Actions.

### Terraform version

1.3.6

### Workflow YAML

```yaml
terraform_plan:
    environment: Github Actions
    name: Terraform Plan QA
    runs-on: QARunner
    needs: terraform_format
    strategy:
      fail-fast: false
      matrix:
        region: [ "us-east-1", "eu-west-1", "ap-southeast-2", "ca-central-1", "ap-northeast-1", "global" ]
    steps:
      - uses: actions/checkout@v3
        name: Checkout Repo

      - name: terraform plan
        uses: dflook/terraform-plan@v1.31.1
        env:
          GITHUB_TOKEN: ${{ secrets.KS_ACCESS_TOKEN }}
          TERRAFORM_PRE_RUN: |
            echo ${{ secrets.KSM_CONFIG }} > config.txt
            base64 -d config.txt > .terraform.config.json
            mv .terraform.config.json ~/.terraform.config.json
        with:
          path: ./terraform/environments/commercial/${{ matrix.region }}/qa
```

### Workflow log

```shell
Initializing the backend...
  ╷
  │ Error: error configuring S3 Backend: no valid credential sources for S3 Backend found.
  │ 
  │ Please see https://www.terraform.io/docs/language/settings/backends/s3.html
  │ for more information about providing credentials.
  │ 
  │ Error: NoCredentialProviders: no valid providers in chain. Deprecated.
  │ 	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
  ```
```
