### ISSUE TITLE
terraform-validate@v1 bug : failure-reason not showing

### ISSUE THREAD

**Issue by roeniss** [dflook/terraform-github-actions#251]
### Problem description

Look at [this action result](https://github.com/roeniss/terraform-up-and-running-practices/actions/runs/4434367145/jobs/7780278218), please.

I made an intentional grammar error and expected that `steps.validate.outputs.failure-reason` has a string value, which is explained [here](https://github.com/dflook/terraform-validate#outputs). 

Am I missing something? By the way, thank you for such a great github actions set.

### Terraform version

1.4.0

### Backend

ㅎithub

### Workflow YAML

```yaml
on: [push]

jobs:
  validate:
    runs-on: ubuntu-latest
    name: Validate terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: terraform validate
        uses: dflook/terraform-validate@v1

      - name: Validate failed
        if: ${{ failure() }}
        run: echo ${{ steps.validate.outputs.failure-reason }}
```

### Workflow log

```shell
I think the first link would be appropriate.
```

**Comment by dflook** [comment]
You are referencing the outputs of a step that doesn't exist. You need to add an id to the validate step:

```yaml

      - name: terraform validate
        id: validate
        uses: dflook/terraform-validate@v1
```
