### ISSUE TITLE
Run terraform-github-actions with -chdir argument?

### ISSUE THREAD

**Issue by y-chen** [dflook/terraform-github-actions#253]
### Problem description

Hello,

I have all my tf files in a `./terraform` folder. In order to make easier to work with the rest of the files in the repository I run terraform cli from the root of the repository using `-chdir terraform`.

I am trying to use `terraform-plan` action but I am having an issue with the paths because how I usually use terraform CLI assumes that is run in the root of the repository but `terraform-plan` runs in `./terraform` folder.

Terraform code works when manually run as below.

How can I make `terraform-plan` without changing the terraform code?

### Terraform version

1.3.7

### Backend

s3

### Workflow YAML

```yaml
# How I usually use terraform in the workflow
- name: Terraform init
  run: terraform -chdir=terraform init...

# How I am using terraform-plan
- name: Terraform plan
  uses: dflook/terraform-plan@v1
  with:
    path: terraform
    backend_config: |
      region=${{ env.TF_VAR_AWS_REGION }}
      bucket=${{ env.TF_VAR_TERRAFORM_BACKEND_BUCKET }}
    var_file: terraform/${{ env.ENVIRONMENT_NAME }}.tfvars
```

### Workflow log

```shell
on locals.tf line 11, in locals:
  11:   version = jsondecode(file("${path.cwd}/package.json")).version
    ├────────────────
    │ while calling file(path)
    │ path.cwd is "/github/workspace/terraform"
```
