### ISSUE TITLE
When in 'remote' planning mode, TFC isn't respecting the '-no-color' flag

### ISSUE THREAD

**Issue by DanyC97** [dflook/terraform-github-actions#270]
### Discussed in https://github.com/dflook/terraform-github-actions/discussions/269

<div type='discussions-op-text'>

<sup>Originally posted by **DanyC97** June 19, 2023</sup>
Hi, 

i thought i should start a convo instead of an issue, if it turns out being valid issue will move it there.

Using tf-plan action and the `cloud` backend type where my workspace is being configured as `remote`  (in the execution mode section), while running a plan and the output is being pushed as a comment i get

```
Running plan in Terraform Cloud. Output will stream here. Pressing Ctrl-C
will stop streaming the logs, but will not stop the plan running remotely.

Preparing the remote plan...

To view this run in a browser, visit:
https://app.terraform.io/app/foo-org/tfc-mgmt/runs/run-mDwwA5RTAopqLAZJ

Waiting for the plan to start...

Terraform v1.4.5
on linux_amd64
Initializing plugins and modules...
�[0m�[1mdata.tfe_team.teams["Release Mgmt"]: Reading...�[0m�[0m
�[0m�[1mtfe_workspace.workspaces["terraform-google-cloudnat"]: Refreshing state... [id=ws-yGr1smKWAavJvD7T]�[0m

...


�[0m�[1m�[32mNo changes.�[0m�[1m Your infrastructure matches the configuration.�[0m

�[0mTerraform has compared your real infrastructure against your configuration
and found no differences, so no changes are needed.
```

Is this expected or am i doing s'thing wrong?

Please note the output seen in TFC UI match the one seen in the GH action job log.

On a different tangent note, when running in `cloud` mode is the expectation for the plan output to be just the url as a comment or what i see above is the right behaviour ?</div>

**Comment by dflook** [comment]
I haven't been able to reproduce this. Can you post the terraform backend config you are using and the workflow? Where do you see this output? in the workflow log, PR comment, or both?

**Comment by DanyC97** [comment]
Sure, give me some time to dig up all the logs, will get back to you shortly 👍

**Comment by DanyC97** [comment]
And found it.

> Where do you see this output? in the workflow log, PR comment, or both?

in the workflow log it looks okay which match what is shown in TFC UI. However in PR comment you see as pe the report with the special chars

### backend

`cat examples/backend_partial_example.tf`
```
terraform {
  cloud {
    organization = "dani-free-org"
  }
}

```


### Reusable workflow

```
name: 🤝 Reusable Terraform Plan

on:
  workflow_call:
    inputs:
      tf_workspace:
        description: "Name of the terraform workspace"
        required: false
        type: string
      tf_path:
        description: "Path to the terraform configuration"
        required: false
        default: .
        type: string
      tf_variables:
        description: "Variable definitions"
        required: false
        type: string
      tf_var_file:
        description: "List of var file paths, one per line"
        required: false
        type: string
      tf_backend_config:
        description: "List of backend config values to set, one per line"
        required: false
        type: string
      tf_backend_config_file:
        description: "Path to a backend config file"
        required: false
        type: string
    secrets:
      tf_api_token:
        description: "Terraform Cloud API token."
        required: true
      gcp_project_id:
        description: "Google Cloud Project id"
        required: false
      gcp_project_number:
        description: "Google Cloud Project number"
        required: false
      gcp_wif_sa_id:
        description: "Google Cloud Workload Identity Federation Service Account id"
        required: false
      gcp_wif_pool_name:
        description: "Google Cloud Workload Identity Federation pool name"
        required: false

# Allow only one of this workflow to run at a time per branch.
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: false

# Allow read repository contents, write deployments and pull requests.
permissions:
  contents: read
  id-token: write
  pull-requests: write

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  tf-plan-run:
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v3.5.2 # v3.5.2

      # unfortunately Github Action interpreter currently doesn't identify
      # the secrets key word when used in an if conditional expression
      - name: Check for input secret availability
        id: secret-check
        # perform secret check & put boolean result as an output
        shell: bash
        run: |
          if [ "${{ secrets.gcp_project_id }}" != '' ] && [ "${{ secrets.gcp_project_number }}" != '' ] && [ "${{ secrets.gcp_wif_sa_id }}" != '' ] && [ "${{ secrets.gcp_wif_pool_name }}" != '' ]; then
            echo "available=true" >> $GITHUB_OUTPUT;
          else
            echo "available=false" >> $GITHUB_OUTPUT;
          fi

      # only if an input param is provided we run otherwise skip
      - name: Setup Google Auth
        if: ${{ steps.secret-check.outputs.available == 'true' }}
        uses: google-github-actions/auth@v1.1.1 # v1.1.1
        with:
          service_account: ${{ secrets.gcp_wif_sa_id }}@${{ secrets.gcp_project_id }}.iam.gserviceaccount.com
          workload_identity_provider: "projects/${{ secrets.gcp_project_number }}/locations/global/workloadIdentityPools/${{ secrets.gcp_wif_pool_name }}/providers/github-provider"
          token_format: access_token
          access_token_lifetime: 300s

      # we need only the minimum config, in our case we have also baked in
      # the org although we could have pass in as env variable
      - name: Render the terraform backend_partial_example.tf file
        shell: bash
        run: |
          cp examples/backend_partial_example.tf backend.tf

      - name: Terraform plan
        uses: dflook/terraform-plan@v1.35.0 # v1.35.0
        env:
          TERRAFORM_CLOUD_TOKENS: app.terraform.io=${{ secrets.tf_api_token }}
          TFE_TOKEN: ${{ secrets.tf_api_token }}
        with:
          workspace: ${{ inputs.tf_workspace }}
          path: ${{ inputs.tf_path }}
          variables: ${{ inputs.tf_variables }}
          var_file: ${{ inputs.tf_var_file }}

```

### Caller workflow

```
name: 🤝 CI/CD Terraform

on:
  pull_request:
    types: [labeled, opened, synchronize]

jobs:
  get-pr-labels:
    runs-on: ubuntu-latest
    outputs:
      pr-details: ${{ steps.get-pull-request.outputs.pr_labels }}

    steps:
      - name: Fetch pull request labels details
        id: get-pull-request
        uses: 8BitJonny/gh-get-current-pr@2.2.0 # v2.2.0
        with:
          # Verbose setting SHA when using Pull_Request event trigger to fix #16. (For push even trigger this is not necessary.)
          sha: ${{ github.event.pull_request.head.sha }}
          # Only return if PR is still open. (By default it returns PRs in any state.)
          filterOutClosed: true

  ci-terraform-plan:
    needs: get-pr-labels
    if: |-
      ${{
        !(contains(needs.get-pr-labels.outputs.pr-details, 'tf:apply') ||
        contains(needs.get-pr-labels.outputs.pr-details, 'tf:auto-apply') )
      }}
    uses: ./.github/workflows/reusable-terraform-plan-run.yml
    with:
      # hardcoded as is different than the repo name
      tf_workspace: tfc-mgmt
      tf_var_file: ./config-tfvars/tfc-config.tfvars
    secrets:
      tf_api_token: ${{ secrets.TFC_API_TOKEN }}

  cd-terraform-apply:
    needs: get-pr-labels
    if: |-
      ${{
        contains(needs.get-pr-labels.outputs.pr-details, 'tf:apply') ||
        contains(needs.get-pr-labels.outputs.pr-details, 'tf:auto-apply')
      }}
    uses: ./.github/workflows/reusable-terraform-apply-run.yml
    with:
      # hardcoded as is different than the repo name
      tf_workspace: tfc-mgmt
      tf_var_file: ./config-tfvars/tfc-config.tfvars
    secrets:
      tf_api_token: ${{ secrets.TFC_API_TOKEN }}

```
