### ISSUE TITLE
Resources are not removed despite the action claiming otherwise

### ISSUE THREAD

**Issue by DawidNiezgodka** [dflook/terraform-github-actions#292]
### Problem description

My workflow architecture consists of a main workflow, dubbed `main-workflow`, that integrates three modular sub-workflows: `workflowA`, `workflowB`, and `workflowC`. `workflowA` employs `dflook/terraform-apply@v1` deploy infrastructure on GCP (this works flawlessly). `workflowB` is designed to perform benchmarks on this deployed infrastructure, while `workflowC` aims to destroy it.

However, I'm encountering an issue. Despite `dflook/terraform-destroy@v1` reporting successful resource removal—stating "Destroy complete! Resources: 16 destroyed"—the resources remain intact and visible within the GCP console, and they're still accessible via SSH.
Currently, the only workaround to completely remove the infrastructure is to rerun the workflow, omitting the initial steps.

I've attached a snippet of the workflow log for your review. Please let me know if there's anything else you'd like to examine.

### Backend

gcs

### Workflow YAML

```yaml
on:
  workflow_call:

jobs:
  deploy:
    permissions:
      contents: write
      id-token: write
    name: Destroy infrastructure on GCP
    runs-on: ${{ vars.RUNNER }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_KEY }}

      - name: Create backend.tf with the definition of a bucket
        uses: DawidNiezgodka/CreateTfBackendFile
        with:
          bucketName: ${{ secrets.GCP_BUCKET_NAME }}

      - name: Create provider.tf
        uses: DawidNiezgodka/CreateTfProviderFileForGCP
        with:
          project: ${{ secrets.GCP_PROJECT }}
          region: ${{ secrets.GCP_REGION }}

      - name: Destroy infrastructure
        uses: dflook/terraform-destroy@v1
        with:
          variables: |
            project = "${{ secrets.GCP_PROJECT }}"
            region = "${{ secrets.GCP_REGION }}"
```

### Workflow log

```shell
module.m1["0"].google_compute_address.external_ip[0]: Destruction complete after 11s
module.m1["0"].google_compute_address.external_ip[2]: Destruction complete after 11s
module.m1["0"].google_compute_address.external_ip[1]: Destruction complete after 11s
google_compute_subnetwork.subnetw[0]: Destruction complete after 13s
google_compute_network.netw: Destroying... [id=...]
google_compute_network.netw: Still destroying... [id=..., 10s elapsed]
google_compute_network.netw: Still destroying... [id=..., 20s elapsed]
google_compute_network.netw: Destruction complete after 22s

Warning: Value for undeclared variable

The root module does not declare a variable named "project" but a value was
found in file "/tmp/variables.tfvars". If you meant to use this value, add a
"variable" block to the configuration.

To silence these warnings, use TF_VAR_... environment variables to provide
certain "global" settings to all configurations in your organization. To
reduce the verbosity of these warnings, use the -compact-warnings option.

Warning: Value for undeclared variable

The root module does not declare a variable named "region" but a value was
found in file "/tmp/variables.tfvars". If you meant to use this value, add a
"variable" block to the configuration.

To silence these warnings, use TF_VAR_... environment variables to provide
certain "global" settings to all configurations in your organization. To
reduce the verbosity of these warnings, use the -compact-warnings option.
Releasing state lock. This may take a few moments...

Destroy complete! Resources: 16 destroyed.

##[debug]Docker Action run completed with exit code 0
```

### Has debug logging been enabled?

- [X] Yes, the `ACTIONS_STEP_DEBUG` secret was set to `true` when capturing the workflow log above.
