### ISSUE TITLE
Allow Plan PR comments to be collapsible

### ISSUE THREAD

**Issue by donovanmuller** [dflook/terraform-github-actions#33]
A large stack plan (via `dflook/terraform-plan`) can generate a large PR comment, it would be great if there was a feature toggle to rather create a [collapsible](https://gist.github.com/pierrejoubert73/902cc94d79424356a8d20be2b382e1ab) plan output instead (or even dynamically based on if the plan output was over a certain amount of characters).

This is suggested in the `hashicorp/setup-terraform` docs under the [Usage](https://github.com/hashicorp/setup-terraform#usage) section. E.g.

```yaml
- uses: actions/github-script@0.9.0
  if: github.event_name == 'pull_request'
  env:
    PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
  with:
    github-token: ${{ secrets.GITHUB_TOKEN }}
    script: |
      const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
      #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
      #### Terraform Validation 🤖${{ steps.validate.outputs.stdout }}
      #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
      
      <details><summary>Show Plan</summary>
      
      \`\`\`${process.env.PLAN}\`\`\`
      
      </details>
      
      *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`${{ env.tf_actions_working_dir }}\`, Workflow: \`${{ github.workflow }}\`*`;
        
      github.issues.createComment({
        issue_number: context.issue.number,
        owner: context.repo.owner,
        repo: context.repo.repo,
        body: output
      })
```
