### ISSUE TITLE
Action is ignoring job.defaults.run.working-directory setting

### ISSUE THREAD

**Issue by flipcc** [dflook/terraform-github-actions#349]
### Problem description

Short description: When setting a default working directory at job level, one can't use a relative path from there for the `path` attribute.

Expected behavior: using relative path from default workding directory works

Actual behavior: it is needed to specify complete path from GitHub workspace

Possible reason: from the logs one can see that docker run command receives GitHub workspace as `workdir` param. This should be changed to recognize any set default working directories.

### Terraform version

1.9.5

### Backend

s3

### Workflow YAML

```yaml
deploy_dev:
    needs: [ setup ]
    defaults:
      run:
        working-directory: ./400_application_layer
    environment: dev
    strategy:
      matrix:
        value: ${{ fromJSON(needs.setup.outputs.app_dir_names) }}
    runs-on: ${{ vars.DEFAULT_RUNNER_OS }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.5"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-central-1
          role-to-assume: arn:aws:iam::${{ vars.ACCOUNT_ID }}:role/cicd
          role-duration-seconds: 1800

      - name: Echo cwd
        run: |
          export matrix_value=${{ matrix.value }}
          if [ -d "$PWD/$matrix_value/terraform" ]; then
            echo "Does exist!" # And it does exist!
          else
            exit 1
          fi

      - name: terraform-apply
        uses: dflook/terraform-apply@v1
        with:
          auto_approve: true
          backend_config: |
            bucket         = ${{ vars.TF_BACKEND_BUCKET }}
            dynamodb_table = ${{ vars.TF_BACKEND_TABLE }}
          label: ${{ vars.WORKSPACE }}
          path: ./${{ matrix.value }}/terraform
          variables: |
            account_id = ${{ vars.ACCOUNT_ID }}
          workspace: ${{ vars.WORKSPACE }}
```

### Workflow log

```shell
Error:  Path does not exist: "./010_hello_world_server/terraform"
```

### Has debug logging been enabled?

- [X] Yes, the `ACTIONS_STEP_DEBUG` secret was set to `true` when capturing the workflow log above.
