### ISSUE TITLE
Terraform Cloud Workspace DESTROY

### ISSUE THREAD

**Issue by fs-david-harrington** [dflook/terraform-github-actions#353]
### Problem description

Conditional checks for Terraform Cloud Workspaces; 
How do I configure my Github action to use the TFC Workspace with the destroy action: dflook/terraform-destroy ?

In the current documentation its not clear how the Github action determines if a local workspace (relative to the path para) is used OR Terraform Cloud Workspace. 

I figured the existence of the env: variable would have been enough: 

- env: TERRAFORM_CLOUD_TOKENS: app.terraform.io=${{ env.TF_API_TOKEN }}

### Backend

Terraform Cloud

### Workflow YAML

```yaml
steps:
    - name: Checkout GitHub Terraform
      uses: actions/checkout@v4
      with:
        sparse-checkout: ${{ env.CONFIG_DIRECTORY }}
    - name: terraform destroy
      env:
        TERRAFORM_CLOUD_TOKENS: app.terraform.io=${{ env.TF_API_TOKEN }}
      uses: dflook/terraform-destroy@v1
      id: first_try
      continue-on-error: true
      with:
        workspace: ${{ env.TF_WORKSPACE }}
    - name: Retry failed destroy
      env:
        TERRAFORM_CLOUD_TOKENS: app.terraform.io=${{ env.TF_API_TOKEN }}
      uses: dflook/terraform-destroy@v1
      if: ${{ steps.first_try.outputs.failure-reason == 'destroy-failed' }}
      with:
        workspace: ${{ env.TF_WORKSPACE }}
```

### Workflow log

```shell
Installing Terraform
Initializing Terraform
Selecting workspace
  
  Workspace "template-aws-lambda-api-dev" doesn't exist.
  
  You can create this workspace with the "new" subcommand 
  or include the "-or-create" flag with the "select" subcommand.
```

### Has debug logging been enabled?

- [X] Yes, the `ACTIONS_STEP_DEBUG` secret was set to `true` when capturing the workflow log above.
