### ISSUE TITLE
Running a plan with matrix loop will minimize the comment for all but one item in the loop and mark them as outdated

### ISSUE THREAD

**Issue by jan-tomsic** [dflook/terraform-github-actions#379]
### Problem description

If you run tofu-plan with `strategy: matrix` and `add_github_comment: always-new` flag, it will mark all but one of the new comments as "outdated" and minimize them

Directory structure looks like this:

./dev
./stg
./prod
./modules

I want to run tofu plan and apply for each of the dev/stg/prod directories separately.

I can see multiple comments, but only the last one is actually shown, the others are minimized. It would be great if it was able to display new comments for each of the matrix items and only minimize them when that same item runs a plan again.

### Terraform version

tofu 1.9.0

### Backend

s3

### Workflow YAML

```yaml
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  tofu-plan:
    strategy:
      matrix:
        environment: [ dev, stg, prod ]

  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: tofu plan
      uses: dflook/tofu-plan@v1
      with:
        path: ${{ matrix.environment }}
        add_github_comment: always-new
```

### Workflow log

```shell

```

### Has debug logging been enabled?

- [x] Yes, the `ACTIONS_STEP_DEBUG` secret was set to `true` when capturing the workflow log above. I understand that if I have not done this, I may not receive a response.

**Comment by dflook** [comment]
Can you share what your backend configuration block looks like, and the name of the file it is defined in?

**Comment by dflook** [comment]
Thanks, it looks like a problem related to the early initialisation variables used in the backend block.

As a workaround, you should be able to set a unique `label` input for each environment.

e.g.
```yaml
      uses: dflook/tofu-plan@v1
      with:
        path: ${{ matrix.environment }}
        label: ${{ matrix.environment }}
        add_github_comment: always-new
```
