### ISSUE TITLE
How to pass the Terraform Token?

### ISSUE THREAD

**Issue by themathmagician** [dflook/terraform-github-actions#40]
Hi there
I am really excited about trying to use your actions, but I am missing to understand, how to authenticate with terraform.
I have added a secret to my repository secrets with the token. How should I pass it to your action?

Here is my job definition:
```
   terraform-plan:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: echo files
        run: echo $(ls -al)
      - name: Terraform - validate configuration
        uses: dflook/terraform-validate@v1
        with:
          path: iac

      - name: Terraform - plan
        uses: dflook/terraform-plan@v1
        with:
          path: iac
```

I am getting the following error:
```
Run dflook/terraform-plan@v1
/usr/bin/docker run --name danielflookterraformgithubactionsv160_cb9713 --label 5588e4 --workdir /github/workspace --rm -e GITHUB_TOKEN -e INPUT_PATH -e INPUT_WORKSPACE -e INPUT_BACKEND_CONFIG -e INPUT_BACKEND_CONFIG_FILE -e INPUT_VAR -e INPUT_VAR_FILE -e INPUT_PARALLELISM -e INPUT_LABEL -e INPUT_ADD_GITHUB_COMMENT -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true --entrypoint "/entrypoints/plan.sh" -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/supercalifragilistic-run-lambda/supercalifragilistic-run-lambda":"/github/workspace" danielflook/terraform-github-actions:v1.6.0

Reading required version from terraform file, constraint: >=0.14.8
Switched terraform to version "0.14.8" 

Initializing the backend...

Error: Required token could not be found

Run the following command to generate a token for app.terraform.io:
    terraform login
```

**Comment by dflook** [comment]
Hi @themathmagician. You can pass it as part of the [backend_config](https://github.com/dflook/terraform-github-actions/tree/master/terraform-plan#inputs) input. It would look something like:

```yaml
      - name: Terraform - plan
        uses: dflook/terraform-plan@v1
        with:
          path: iac
          backend_config: "token=${{ secrets.TF_API_TOKEN }}"
```
