### ISSUE TITLE
Not respecting existing known_hosts and ssh setup

### ISSUE THREAD

**Issue by akaltar** [dflook/terraform-github-actions#41]
I'm trying to use this action with a terraform project that imports its submodules from another (private) repository.

This is the type of error I'm getting:

```
Error: Failed to download module

Could not download module "database" (../../layers/data/main.tf:1) source code
from "git@github.com:veedstudio/veed-terraform-modules.git?ref=master": error
downloading
'ssh://git@github.com/veedstudio/veed-terraform-modules.git?ref=master':
/usr/bin/git exited with 128: Cloning into
'/github/home/.dflook-terraform-data-dir/modules/data.database'...
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Even though if I run `git clone` before this, it does work as expected, and the action I use before adds the correct `known_hosts` values for github.com. here is the relevant snippet from the workflow I'm writing:

```
      - name: Set up access key for terraform_modules repo
        uses: webfactory/ssh-agent@v0.5.1
        with:
          ssh-private-key: ${{ secrets.GH_SSH_PRIVATE_KEY }}

      - name: Debug
        run: git clone ssh://git@github.com/veedstudio/veed-terraform-modules.git && ls

      - name: terraform plan
        uses: dflook/terraform-plan@v1
        with:
          path: environments/dev
```

Based on the logs it looks like this action is using a different home directory and runs inside a docker container, hence why it may not take into account the SSH setup?
I assume fixing this may require changes to the action, I'd just like some help about how to go about this.
Thank you for this super handy action library.
