### ISSUE TITLE
Workspace input not working 

### ISSUE THREAD

**Issue by holzro** [dflook/terraform-github-actions#5]
The workspace input on each github action is not working, I am using a prefix in my terraform backend configuration. I am using the following code 

```
name: Check for terraform drift

on: [push]

jobs:
  check_drift:
    runs-on: ubuntu-latest
    name: Check for drift of example terraform configuration
    strategy:
      max-parallel: 1
      matrix:
        workspace: [dev, uat, prod]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          path: terraform

      - name: Check for drift
        uses: dflook/terraform-check@v1
        env:
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
        with:
          path: terraform
          workspace: ${{ matrix.workspace }}
          backend_config: "token=${{ secrets.TF_API_TOKEN }}"
```

And when I run this action I am getting the following result

```
Run dflook/terraform-check@v1
  with:
    path: terraform
    workspace: dev
    backend_config: token=***
    parallelism: 0
  env:
    TF_API_TOKEN: ***
/usr/bin/docker run --name danielflookterraformgithubactionsv120_fe4448 --label 87c201 --workdir /github/workspace --rm -e TF_API_TOKEN -e INPUT_PATH -e INPUT_WORKSPACE -e INPUT_BACKEND_CONFIG -e INPUT_BACKEND_CONFIG_FILE -e INPUT_VAR -e INPUT_VAR_FILE -e INPUT_PARALLELISM -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true --entrypoint "/entrypoints/check.sh" -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/dotnet-azure-connect-githubpoc-terraform/dotnet-azure-connect-githubpoc-terraform":"/github/workspace" danielflook/terraform-github-actions:v1.2.0

Reading latest terraform version
Switched terraform to version "0.12.28" 

Initializing the backend...

Successfully configured the backend "remote"! Terraform will automatically
use this backend unless the backend configuration changes.

Error: Failed to select workspace: input not a valid number



The currently selected workspace (default) does not exist.
  This is expected behavior when the selected workspace did not have an
  existing non-empty state. Please enter a number to select a workspace:
  
  1. dev
  2. prod
  3. uat

  Enter a value: 
```

I have also tried using the workspace name and number, these also did not work
