### ISSUE TITLE
Retry functionality

### ISSUE THREAD

**Issue by donovanmuller** [dflook/terraform-github-actions#71]
I would greatly appreciate a "retry" feature. Due to various environmental or flaky Terraform providers, sometimes a `plan` or `apply` will fail for some innocuous reason and when the job is re-run, it then completes successfully.

A native retry feature similar to [nick-invision/retry](https://github.com/marketplace/actions/retry-step) would be quite useful for me, hopefully it would be for others?

**Comment by dflook** [comment]
The problem with automatically retrying is that the plan is most likely different on the second attempt. So whatever approval had been given for the first attempt could result in unintended changes on the second attempt.

If terraform had a native feature that only retried failed changes from an already approved plan, I would definately add it.

If you're happy to accept the risk, you could add another `auto_approve` apply step that only runs if the first one fails:

```yaml
steps:
  - name: Checkout
    uses: actions/checkout@v2

  - name: Apply
    uses: dflook/terraform-apply@1
    continue-on-error: true
    id: first_try
    with:
      path: my_terraform

  - name: Retry failed apply
    uses: dflook/terraform-apply@1
    if: ${{ steps.first_try.outcome == 'failure' }}
    with:
      path: my_terraform
      auto_approve: true
```

**Comment by donovanmuller** [comment]
Thanks, makes sense. I'll give the suggestion a bash

**Comment by dflook** [comment]
Actually, that's probably a bad idea - if the first try failed because the plan had changed, the second try would apply it anyway! I think this can work but it needs some more thought

**Comment by dflook** [comment]
v1.15.0 has been released which has a `failure-reason` output for the apply action.

This means you can now safely retry only when the apply operation failed:

```yaml
steps:
  - name: Checkout
    uses: actions/checkout@v2

  - name: Apply
    uses: dflook/terraform-apply@v1
    continue-on-error: true
    id: first_try
    with:
      path: my_terraform

  - name: Retry failed apply
    uses: dflook/terraform-apply@v1
    if: ${{ steps.first_try.outputs.failure-reason == 'apply-failed' }}
    with:
      path: my_terraform
      auto_approve: true
```
