### ISSUE TITLE
Terraform Variables

### ISSUE THREAD

**Issue by xylene314** [dflook/terraform-github-actions#90]
Hi @dflook ,

I have a question on how to pass `TF_VAR_` from the CI to the terraform file?

Please advise

**Comment by dflook** [comment]
You can set environment variables for these actions in the normal way, e.g.
```yaml
      - name: Plan
        uses: dflook/terraform-plan@v1
        env:
          TF_VAR_my_variable: "hello"
        with:
          path: terraform
```
A nicer way to use input variables is with the `variables` input:
```yaml
      - name: Plan
        uses: dflook/terraform-plan@v1
        with:
          variables: |
            my_variable="hello"
```

See the [terraform-plan](https://github.com/dflook/terraform-github-actions/tree/master/terraform-plan#inputs) docs for details
